Added Passport Authentication
cbrtl/ratenect-backend pull request #22
Opened 2021-08-11 19:32 UTC by Ankur-Khandelwal

2021-08-11 20:17 UTC, srijan-paul requested changes

2021-08-11 20:17 UTC, srijan-paul commented on routes/ngo.js
> +    else{
Prettier check would catch this.

2021-08-11 20:17 UTC, srijan-paul commented on routes/ngo.js
> +  req.login(ngo, (error)=>{
Formatting issue in this (and subsequent) block as well. A lot of this can be automated with a simple CI run.

2021-08-11 20:17 UTC, srijan-paul commented on routes/ngo.js
> +
Looks like there's way too many newlines?
There should be one newline at EOF. (Can also be detected with ESLint)

2021-08-11 20:17 UTC, srijan-paul commented on routes/user.js
> +module.exports = router;
This file is missing a linefeed at EOF.

2021-08-11 20:17 UTC, srijan-paul commented on src/index.js
> +const dbName = process.env.dbName;
environment constants should be all caps.
Because that's how the shell is supposed to be seeing them.

2021-08-11 20:17 UTC, srijan-paul commented on src/index.js
> +var userType = "";
Never use `var` for anything. It's pretty much soft deprecated in ES6.
(I know some old guides/articles use it, but `var` is terrible, and has no usecase today)

2021-08-11 20:17 UTC, srijan-paul commented on src/index.js
> +passport.deserializeUser(function(id, done) {
the parameter name `done` suggests it's a boolean (to the reader).
A better name would be `onComplete`, or `resolve`. 
Note also that there is no error handling here.

2021-08-11 20:17 UTC, srijan-paul commented on src/index.js
> +})
newline at EOF here as well.

2021-08-11 20:38 UTC, srijan-paul commented
A lot here can be corrected by judicious use of ESLint/Prettier. (and Github Actions)
There are no tests for the endpoints that exist currently, so I can't make any claims/corrections about the business logic.

One thing did I notice however, is the error callbacks are bit too tedious here (especially when nested).
You don't need to get into callback hell for mongoose, or express. Almost every function that takes an error callback, also has a version that can return a promise instead. So it's cleaner to use async await.

As a bonus,
Here is a neat trick (decorator pattern?) that you can use to avoid them:

```js
function decorate(func) {
  return async function (...args)  {
    const result = func(...args);
    try {
      return [false, result]
    } catch (err) {
      return [err, false];
    }
  }
}
```

Now, old code (from the diff):

```js
User.register({name, email}, password, function(err, user){
	if (err) {
    return res.status(401).json({ message: err.message });
  } else {
		if (user) return res.status(201).json({ message: "Account created successfully", newUser: user });
		else return res.status(400).json({ message: "Sorry. Your account couldn't be created"});
  }
})
```

And new code:

```js
User.register = decorate(User.register)

const [err, user] = await User.register({name, email}, password)
if (err) return res.status(401).json(message: err.message);
if (user) return res.status(201).json({ message: "Account created successfully", newUser: user });
return res.status(400).json({ message: "Sorry. Your account couldn't be created"});
```

This is much easier to follow, and when there are multiple levels of nesting, we don't have to rely on ugly callbacks.

---

Another small nitpick: You can use more destructuring.

```js
const { email, username, password } = req.body
User.register( { name, email }, password, (err, res) => { ... });
```

Instead of the current:

```js
User.register( { name: req.body.name, email: req.body.email }, req.body.password, (err, res) => { ... })
```

---

There are some other issues too (like the current API is very hard to test because all logic is in the HTTP method handlers instead of a separate implementation etc), but I think the alarming problem now is the possibility of poorly formatted and linted code making it into the mainline. (The 50 or so newlines for example).

Anyone can inject malicious code with a huge diff and it'll get merged if not reviewed with extreme care, which is not likely for most reviews.

2021-08-12 07:53 UTC, Ankur-Khandelwal commented
Thank you for the in-depth review @srijan-paul. I shall implement the eslint and prettier immediately. However for the decorator pattern with async and await, I will have to learn more. So we shall implement them after that.

2021-08-13 07:00 UTC, merged